name: Deploy to Azure Web App container

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./src
        push: true
        tags: lucasmchagas23/projeto_integrador_comparador:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: comparadorapi
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: lucasmchagas23/projeto_integrador_comparador:latest
